name: "Zoho Calendar"
description: "Integrazione calendario Zoho Service Management per Home Assistant"
version: "1.0.19"
slug: "zoho-calendar"
url: "https://github.com/emironet/ha-addons/tree/main/zoho-calendar"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
init: false
boot: auto
icon: icon.png
ingress: true
ingress_port: 8099
panel_icon: "mdi:calendar-clock"
panel_title: "Zoho Calendario"
map:
  - config:rw
services:
  - mqtt:want
options:
  update_interval: 60
  mqtt_topic_prefix: "zoho_calendar"
schema:
  update_interval: int
  mqtt_topic_prefix: str
